dist: trusty
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
# Remove the './node_modules/.bin:' entry, see https://github.com/travis-ci/travis-ci/issues/8813
- export PATH=`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'`
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "WV06jIHv6atKSYZxKk4Slo0Gfmv6fRgkWU2GGVTcwVzitypieMvEyZeRJwznDQAA+2QafEeMwjonZYA7OY8t+vsEbGO3FXQvFaWx5IPevhXxVeDVPhKsTXLoI3cHx25nJA6uPZaQPVtqpoKOeMKvMrGuwaMhYYTkRyuTmUVqh7H89gbcTx35/Bz+GaSbVWX2AIVViXjxfrTvm11VPhGAafuku64uSXltj00NdkXBmnxgDtOPblq1eXxzcqJT7jSs/PDZpsvDfQNcNrCIvTeL4iww7eExbXXSQi1fAFV2KIFhrm31ogaxlKqFjbizr+3x6/8RFqy296yJQ0iRRl4sFW7PVpl8l4HuWR1je3BlkQsp+J4W+9t+S19yC9WP/Sqlv3yyNjchBQpjgAWawp36zP0SW1hO/vQ4OFtQc1rYpgbRMqmXU8ofe+rVwqid5e8sZ06jYmpCUiJRB5RU0YPAjKoKrfXIVqHeezVn/JvnXqe2gR4PvqxlRwd1wNbkIqnA55cwMEt0zBO/0DUSjcj/ooo4VZGohHe6t03jFgFoRSvN4zcmSf46FHED5MsYDy+MRwsoguf3D/jowjltrdvjpSAjRSY771ZXMVrnboMgSR14JRnCPlh/y2jrjO48iLLm1Z+YFhWUhbXDz+BqFB4P2Nfbq3V+cjvPJOM1Mv1DJO8="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
